Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -100,40 +100,40 @@ jobs:
         run: trivy image ${{ secrets.DOCKER_USERNAME }}/vng-api:${{ github.sha }}
           
   deploy:
-  runs-on: ubuntu-latest
-  needs: trivy-scan
-  steps: 
-    - name: Decode EC2 Key
-      run: |
-        mkdir -p ~/.ssh
-        echo "${{ secrets.EC2_KEY }}" | base64 --decode > ~/.ssh/ec2-key.pem
-        ls -l ~/.ssh  # List files to ensure the key is created
-        
-    - name: Set permissions for EC2 key
-      run: |
-        chmod 600 ~/.ssh/ec2-key.pem
-        ls -l ~/.ssh  # Verify permissions
-
-    - name: Deploy to EC2
-      env:
-        EC2_USER: ubuntu
-        EC2_HOST: ${{ secrets.EC2_HOST }}
-        EC2_KEY_PATH: ~/.ssh/ec2-key.pem
-        DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/audio-app:${{ github.sha }}
-      run: |
-        ssh -o StrictHostKeyChecking=no -i $EC2_KEY_PATH $EC2_USER@$EC2_HOST <<EOF
-          # Clean up previous containers and images
-          docker stop vng-app || true
-          docker rm -f vng-app || true
-          docker rmi -f $DOCKER_IMAGE || true
+    runs-on: ubuntu-latest
+    needs: trivy-scan
+    steps: 
+      - name: Decode EC2 Key
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ secrets.EC2_KEY }}" | base64 --decode > ~/.ssh/ec2-key.pem
+          ls -l ~/.ssh  # List files to ensure the key is created
           
-          # Pull the new Docker image
-          docker pull $DOCKER_IMAGE
-          
-          # Run the new container with Nginx and Let's Encrypt
-          docker run -dp 3000:8080 \
-            --name vng-app \
-            --mount type=volume,source=letsencrypt,target=/etc/letsencrypt \
-            $DOCKER_IMAGE
-        EOF
+      - name: Set permissions for EC2 key
+        run: |
+          chmod 600 ~/.ssh/ec2-key.pem
+          ls -l ~/.ssh  # Verify permissions
+  
+      - name: Deploy to EC2
+        env:
+          EC2_USER: ubuntu
+          EC2_HOST: ${{ secrets.EC2_HOST }}
+          EC2_KEY_PATH: ~/.ssh/ec2-key.pem
+          DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/audio-app:${{ github.sha }}
+        run: |
+          ssh -o StrictHostKeyChecking=no -i $EC2_KEY_PATH $EC2_USER@$EC2_HOST <<EOF
+            # Clean up previous containers and images
+            docker stop vng-app || true
+            docker rm -f vng-app || true
+            docker rmi -f $DOCKER_IMAGE || true
+            
+            # Pull the new Docker image
+            docker pull $DOCKER_IMAGE
+            
+            # Run the new container with Nginx and Let's Encrypt
+            docker run -dp 3000:8080 \
+              --name vng-app \
+              --mount type=volume,source=letsencrypt,target=/etc/letsencrypt \
+              $DOCKER_IMAGE
+          EOF
 
